<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED>

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Action*,Summary?,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,NodeArgs) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Romance Standard Time">
	<General productName="QuickTest Professional" productVer="9.2" os="Windows XP" host="EBANK-BUILDXP">
		<DocLocation><![CDATA[G:\Departments\IT-Testing\Public\QTP\EncodeSepa\EncodeSEPA]]></DocLocation>
	</General>
	<Doc rID="T1" productName="QuickTest Professional">
		<DName><![CDATA[EncodeSEPA]]></DName>
		<Res><![CDATA[24]]></Res>
		<DT rID="T2">
			<NodeArgs eType="Table" icon="2" nRep="5" filter="False">
				<Disp><![CDATA[Run-Time Data Table]]></Disp>
				<BtmPane vType="Table">
					<Path><![CDATA[Default.xls]]></Path>
				</BtmPane>
			</NodeArgs>
		</DT>
		<DIter rID="T3" iterID="1">
			<Action rID="T4">
				<AName><![CDATA[InitializeSepaEncoding]]></AName>
				<Action rID="T5">
					<AName><![CDATA[Prerequisites [SmokeTest]]]></AName>
					<Summary sTime="16/11/2009 - 17:41:00" eTime="16/11/2009 - 17:41:08" passed="0" failed="0" warnings="0"></Summary>
					<NodeArgs eType="StartAction" icon="5" nRep="9">
						<Disp><![CDATA[Prerequisites [SmokeTest] Summary]]></Disp>
					</NodeArgs>
				</Action>
				<Action rID="T6">
					<AName><![CDATA[LogonIBS6 [SmokeTest]]]></AName>
					<Step rID="T7">
						<Obj><![CDATA[=== START ACTION : LogonIBS6 [SmokeTest] ===]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:08]]></Time>
						<NodeArgs eType="User" icon="6" nRep="12">
							<Disp><![CDATA[=== START ACTION : LogonIBS6 [SmokeTest] ===]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T8">
						<Obj><![CDATA[IBS6 was not yet open, so launch it...]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:11]]></Time>
						<NodeArgs eType="User" icon="6" nRep="15" status="Passed">
							<Disp><![CDATA[IBS6 was not yet open, so launch it...]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T9">
						<Obj><![CDATA[2 names were found in list of certificates]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:15]]></Time>
						<NodeArgs eType="User" icon="6" nRep="19" status="Passed">
							<Disp><![CDATA[2 names were found in list of certificates]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T10">
						<Obj><![CDATA[strData (certificate to select)=TomCert2]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:15]]></Time>
						<NodeArgs eType="User" icon="6" nRep="20" status="Passed">
							<Disp><![CDATA[strData (certificate to select)=TomCert2]]></Disp>
						</NodeArgs>
					</Step>
					<Action rID="T11">
						<AName><![CDATA[SelectLogonProfile]]></AName>
						<Step rID="T12">
							<Obj><![CDATA[LogonProfile1 found on portal.]]></Obj>
							<Details><![CDATA[]]>
							</Details>
							<Time><![CDATA[16/11/2009 - 17:41:31]]></Time>
							<NodeArgs eType="User" icon="6" nRep="40" status="Passed">
								<Disp><![CDATA[LogonProfile1 found on portal.]]></Disp>
							</NodeArgs>
						</Step>
						<Summary sTime="16/11/2009 - 17:41:30" eTime="16/11/2009 - 17:41:34" passed="1" failed="0" warnings="0"></Summary>
						<NodeArgs eType="StartAction" icon="5" nRep="34" status="Passed">
							<Disp><![CDATA[SelectLogonProfile Summary]]></Disp>
						</NodeArgs>
					</Action>
					<Summary sTime="16/11/2009 - 17:41:08" eTime="16/11/2009 - 17:41:34" passed="3" failed="0" warnings="0"></Summary>
					<NodeArgs eType="StartAction" icon="5" nRep="11" status="Passed">
						<Disp><![CDATA[LogonIBS6 [SmokeTest] Summary]]></Disp>
					</NodeArgs>
				</Action>
				<Action rID="T13">
					<AName><![CDATA[DeleteTransactions [SmokeTest]]]></AName>
					<Step rID="T14">
						<Obj><![CDATA[=== START ACTION : DeleteTransactions [SmokeTest] ===]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:34]]></Time>
						<NodeArgs eType="User" icon="6" nRep="47">
							<Disp><![CDATA[=== START ACTION : DeleteTransactions [SmokeTest] ===]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T15">
						<Obj><![CDATA[Go to page 11]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:36]]></Time>
						<NodeArgs eType="User" icon="6" nRep="52" status="Passed">
							<Disp><![CDATA[Go to page 11]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T16">
						<Obj><![CDATA[Confirmation to delete has appeared]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:41]]></Time>
						<NodeArgs eType="User" icon="6" nRep="65" status="Passed">
							<Disp><![CDATA[Confirmation to delete has appeared]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T17">
						<Obj><![CDATA[Go to page 11]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:44]]></Time>
						<NodeArgs eType="User" icon="6" nRep="69" status="Passed">
							<Disp><![CDATA[Go to page 11]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T18">
						<Obj><![CDATA[Confirmation to delete has appeared]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:50]]></Time>
						<NodeArgs eType="User" icon="6" nRep="82" status="Passed">
							<Disp><![CDATA[Confirmation to delete has appeared]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T19">
						<Obj><![CDATA[Go to page 11]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:52]]></Time>
						<NodeArgs eType="User" icon="6" nRep="86" status="Passed">
							<Disp><![CDATA[Go to page 11]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T20">
						<Obj><![CDATA[Confirmation to delete has appeared]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:41:58]]></Time>
						<NodeArgs eType="User" icon="6" nRep="99" status="Passed">
							<Disp><![CDATA[Confirmation to delete has appeared]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T21">
						<Obj><![CDATA[Go to page 11]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:42:00]]></Time>
						<NodeArgs eType="User" icon="6" nRep="103" status="Passed">
							<Disp><![CDATA[Go to page 11]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T22">
						<Obj><![CDATA[Confirmation to delete has appeared]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[16/11/2009 - 17:42:05]]></Time>
						<NodeArgs eType="User" icon="6" nRep="116" status="Passed">
							<Disp><![CDATA[Confirmation to delete has appeared]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T23">
						<Obj><![CDATA[Transactions have been deleted]]></Obj>
						<Details><![CDATA[Number of pages : now = 10 , initial = 14]]></Details>
						<Time><![CDATA[16/11/2009 - 17:42:07]]></Time>
						<NodeArgs eType="User" icon="6" nRep="120" status="Passed">
							<Disp><![CDATA[Transactions have been deleted]]></Disp>
						</NodeArgs>
					</Step>
					<Summary sTime="16/11/2009 - 17:41:34" eTime="16/11/2009 - 17:42:08" passed="9" failed="0" warnings="0"></Summary>
					<NodeArgs eType="StartAction" icon="5" nRep="46" status="Passed">
						<Disp><![CDATA[DeleteTransactions [SmokeTest] Summary]]></Disp>
					</NodeArgs>
				</Action>
				<Action rID="T24">
					<AName><![CDATA[StartEncodeSepa]]></AName>
					<AIter rID="T25" iterID="1">
						<Step rID="T26">
							<Obj><![CDATA[Test : fill in remittance info]]></Obj>
							<Details><![CDATA[]]>
							</Details>
							<Time><![CDATA[16/11/2009 - 17:42:09]]></Time>
							<NodeArgs eType="User" icon="6" nRep="129">
								<Disp><![CDATA[Test : fill in remittance info]]></Disp>
							</NodeArgs>
						</Step>
						<Action rID="T27">
							<AName><![CDATA[aEncodeSepa1]]></AName>
							<Step rID="T28">
								<Obj><![CDATA[Test  1]]></Obj>
								<Details><![CDATA[Arrow A3 was already down...]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:25]]></Time>
								<NodeArgs eType="User" icon="6" nRep="169">
									<Disp><![CDATA[Test  1]]></Disp>
								</NodeArgs>
							</Step>
							<Summary sTime="16/11/2009 - 17:42:11" eTime="16/11/2009 - 17:42:25" passed="0" failed="0" warnings="0">
								<Param paramInOut="Out">
									<ParamName><![CDATA[intResultAction]]></ParamName>
									<ParamVal><![CDATA[<Not Initialized>]]></ParamVal>
								</Param>
							</Summary>
							<NodeArgs eType="StartAction" icon="7" nRep="138">
								<Disp><![CDATA[aEncodeSepa1 Summary]]></Disp>
							</NodeArgs>
						</Action>
						<Action rID="T29">
							<AName><![CDATA[aEncodeSepa3]]></AName>
							<Summary sTime="16/11/2009 - 17:42:25" eTime="16/11/2009 - 17:42:26" passed="0" failed="0" warnings="0"></Summary>
							<NodeArgs eType="StartAction" icon="7" nRep="171">
								<Disp><![CDATA[aEncodeSepa3 Summary]]></Disp>
							</NodeArgs>
						</Action>
						<Action rID="T30">
							<AName><![CDATA[aValidateSepaPayment]]></AName>
							<Step rID="T31">
								<Obj><![CDATA[No confirmation appeared as  expected]]></Obj>
								<Details><![CDATA[]]>
								</Details>
								<Time><![CDATA[16/11/2009 - 17:42:31]]></Time>
								<NodeArgs eType="User" icon="6" nRep="198" status="Passed">
									<Disp><![CDATA[No confirmation appeared as  expected]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T32">
								<Obj><![CDATA[Blue error-bar appeared (2)]]></Obj>
								<Details><![CDATA[Blue error-bar appeared but was empty / not visible. As expected (case 'next transaction' or 'confirmation').]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:32]]></Time>
								<NodeArgs eType="User" icon="6" nRep="200" status="Passed">
									<Disp><![CDATA[Blue error-bar appeared (2)]]></Disp>
								</NodeArgs>
							</Step>
							<Summary sTime="16/11/2009 - 17:42:26" eTime="16/11/2009 - 17:42:32" passed="2" failed="0" warnings="0">
								<Param paramInOut="Out">
									<ParamName><![CDATA[intResultAction]]></ParamName>
									<ParamVal><![CDATA[0]]></ParamVal>
								</Param>
							</Summary>
							<NodeArgs eType="StartAction" icon="7" nRep="181" status="Passed">
								<Disp><![CDATA[aValidateSepaPayment Summary]]></Disp>
							</NodeArgs>
						</Action>
						<Action rID="T33">
							<AName><![CDATA[aCheckDataAfterNextTransactionClick]]></AName>
							<Step rID="T34">
								<Obj><![CDATA[Test 1  --> Originator data]]></Obj>
								<Details><![CDATA[Originator data does correspond to the data in the excelsheet.]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:32]]></Time>
								<NodeArgs eType="User" icon="6" nRep="204" status="Passed">
									<Disp><![CDATA[Test 1  --> Originator data]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T35">
								<Obj><![CDATA[Test 1  --> Memodata and amount]]></Obj>
								<Details><![CDATA[Memodate and amount are empty, as expected.]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:32]]></Time>
								<NodeArgs eType="User" icon="6" nRep="205" status="Passed">
									<Disp><![CDATA[Test 1  --> Memodata and amount]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T36">
								<Obj><![CDATA[Test 1 --> Remittance info]]></Obj>
								<Details><![CDATA[Remmittance Info 1 is empty, as expected.]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:32]]></Time>
								<NodeArgs eType="User" icon="6" nRep="206" status="Passed">
									<Disp><![CDATA[Test 1 --> Remittance info]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T37">
								<Obj><![CDATA[Test 1 --> Remittance info]]></Obj>
								<Details><![CDATA[Remmittance Info 2 is empty, as expected.]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:33]]></Time>
								<NodeArgs eType="User" icon="6" nRep="207" status="Passed">
									<Disp><![CDATA[Test 1 --> Remittance info]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T38">
								<Obj><![CDATA[Test 1 --> Remittance info]]></Obj>
								<Details><![CDATA[Remmittance Info 3 is empty, as expected.]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:33]]></Time>
								<NodeArgs eType="User" icon="6" nRep="208" status="Passed">
									<Disp><![CDATA[Test 1 --> Remittance info]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T39">
								<Obj><![CDATA[Test 1 --> Remittance info]]></Obj>
								<Details><![CDATA[Remmittance Info 4 is empty, as expected.]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:33]]></Time>
								<NodeArgs eType="User" icon="6" nRep="209" status="Passed">
									<Disp><![CDATA[Test 1 --> Remittance info]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T40">
								<Obj><![CDATA[Test 1 --> benef data]]></Obj>
								<Details><![CDATA[Data of beneficiary is empty, as expected]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:33]]></Time>
								<NodeArgs eType="User" icon="6" nRep="210" status="Passed">
									<Disp><![CDATA[Test 1 --> benef data]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T41">
								<Obj><![CDATA[Test 1  --> structured message]]></Obj>
								<Details><![CDATA[Structured message is empty, as expected]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:33]]></Time>
								<NodeArgs eType="User" icon="6" nRep="211" status="Passed">
									<Disp><![CDATA[Test 1  --> structured message]]></Disp>
								</NodeArgs>
							</Step>
							<Summary sTime="16/11/2009 - 17:42:32" eTime="16/11/2009 - 17:42:33" passed="8" failed="0" warnings="0"></Summary>
							<NodeArgs eType="StartAction" icon="7" nRep="202" status="Passed">
								<Disp><![CDATA[aCheckDataAfterNextTransactionClick Summary]]></Disp>
							</NodeArgs>
						</Action>
						<Step rID="T42">
							<Obj><![CDATA[Test 1]]></Obj>
							<Details><![CDATA['Next transaction' has been clicked, but we are going to cancel the payment in order to verify/modify.]]></Details>
							<Time><![CDATA[16/11/2009 - 17:42:33]]></Time>
							<NodeArgs eType="User" icon="6" nRep="213">
								<Disp><![CDATA[Test 1]]></Disp>
							</NodeArgs>
						</Step>
						<Action rID="T43">
							<AName><![CDATA[aCancelSepaPayment]]></AName>
							<Step rID="T44">
								<Obj><![CDATA[Cancel payment]]></Obj>
								<Details><![CDATA[Blue error bar appeared, so cancel the payment and restart the encoding.]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:33]]></Time>
								<NodeArgs eType="User" icon="6" nRep="215">
									<Disp><![CDATA[Cancel payment]]></Disp>
								</NodeArgs>
							</Step>
							<Summary sTime="16/11/2009 - 17:42:33" eTime="16/11/2009 - 17:42:35" passed="0" failed="0" warnings="0"></Summary>
							<NodeArgs eType="StartAction" icon="7" nRep="214">
								<Disp><![CDATA[aCancelSepaPayment Summary]]></Disp>
							</NodeArgs>
						</Action>
						<Action rID="T45">
							<AName><![CDATA[aVerifySepaEncoding]]></AName>
							<Step rID="T46">
								<Obj><![CDATA[GoToDetails of filename = ]]></Obj>
								<Details><![CDATA[EBANK-BUILDXP_20091116174225_1]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:35]]></Time>
								<NodeArgs eType="User" icon="6" nRep="223">
									<Disp><![CDATA[GoToDetails of filename = ]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T47">
								<Obj><![CDATA[     Verify  --> Ordering party account]]></Obj>
								<Details><![CDATA[Actual=BE32135070521402 ; Expected=BE32135070521402]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:38]]></Time>
								<NodeArgs eType="User" icon="6" nRep="236" status="Passed">
									<Disp><![CDATA[     Verify  --> Ordering party account]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T48">
								<Obj><![CDATA[     Verify  --> Beneficiary name]]></Obj>
								<Details><![CDATA[Actual=SEPA test 1 ; Expected=SEPA test 1]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:38]]></Time>
								<NodeArgs eType="User" icon="6" nRep="241" status="Passed">
									<Disp><![CDATA[     Verify  --> Beneficiary name]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T49">
								<Obj><![CDATA[     Verify  --> Beneficiary account]]></Obj>
								<Details><![CDATA[Actual=BE06 1351 1100 1522 ; Expected=BE06 1351 1100 1522]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:38]]></Time>
								<NodeArgs eType="User" icon="6" nRep="248" status="Passed">
									<Disp><![CDATA[     Verify  --> Beneficiary account]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T50">
								<Obj><![CDATA[     Verify  --> Amout Currency]]></Obj>
								<Details><![CDATA[Actual=1,00 EUR ; Expected=1,00 EUR]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:39]]></Time>
								<NodeArgs eType="User" icon="6" nRep="256" status="Passed">
									<Disp><![CDATA[     Verify  --> Amout Currency]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T51">
								<Obj><![CDATA[     Verify  --> Memo date]]></Obj>
								<Details><![CDATA[Actual=16/11/09 ; Expected=16/11/09]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:39]]></Time>
								<NodeArgs eType="User" icon="6" nRep="265" status="Passed">
									<Disp><![CDATA[     Verify  --> Memo date]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T52">
								<Obj><![CDATA[     Verify  --> User reference (end2end identifier)]]></Obj>
								<Details><![CDATA[Actual=200911161742190099ISABEL ; Expected=200911161742190099ISABEL]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:40]]></Time>
								<NodeArgs eType="User" icon="6" nRep="276" status="Passed">
									<Disp><![CDATA[     Verify  --> User reference (end2end identifier)]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T53">
								<Obj><![CDATA[     Verify  --> beneficiary bank BIC]]></Obj>
								<Details><![CDATA[Actual=ABERBE21 ; Expected=ABERBE21]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:40]]></Time>
								<NodeArgs eType="User" icon="6" nRep="290" status="Passed">
									<Disp><![CDATA[     Verify  --> beneficiary bank BIC]]></Disp>
								</NodeArgs>
							</Step>
							<Summary sTime="16/11/2009 - 17:42:35" eTime="16/11/2009 - 17:42:42" passed="7" failed="0" warnings="0"></Summary>
							<NodeArgs eType="StartAction" icon="7" nRep="222" status="Passed">
								<Disp><![CDATA[aVerifySepaEncoding Summary]]></Disp>
							</NodeArgs>
						</Action>
						<Action rID="T54">
							<AName><![CDATA[aModifySepaPayment]]></AName>
							<Step rID="T55">
								<Obj><![CDATA[GoToDetails of filename = ]]></Obj>
								<Details><![CDATA[EBANK-BUILDXP_20091116174225_1]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:44]]></Time>
								<NodeArgs eType="User" icon="6" nRep="299">
									<Disp><![CDATA[GoToDetails of filename = ]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T56">
								<Obj><![CDATA[     Verify  --> Originator Alias]]></Obj>
								<Details><![CDATA[Actual=STG 4 only to range 600 ; Expected=STG 4 only to range 600]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:50]]></Time>
								<NodeArgs eType="User" icon="6" nRep="311" status="Passed">
									<Disp><![CDATA[     Verify  --> Originator Alias]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T57">
								<Obj><![CDATA[     Verify  --> Originator Name]]></Obj>
								<Details><![CDATA[Actual=STG 4 only to range 600 ; Expected=STG 4 only to range 600]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:50]]></Time>
								<NodeArgs eType="User" icon="6" nRep="312" status="Passed">
									<Disp><![CDATA[     Verify  --> Originator Name]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T58">
								<Obj><![CDATA[     Verify  --> Ordering account number]]></Obj>
								<Details><![CDATA[Actual=BE32 1350 7052 1402 ; Expected=BE32 1350 7052 1402]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:50]]></Time>
								<NodeArgs eType="User" icon="6" nRep="313" status="Passed">
									<Disp><![CDATA[     Verify  --> Ordering account number]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T59">
								<Obj><![CDATA[     Verify  --> Principal Amount]]></Obj>
								<Details><![CDATA[Actual=1 ; Expected=1]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:50]]></Time>
								<NodeArgs eType="User" icon="6" nRep="314" status="Passed">
									<Disp><![CDATA[     Verify  --> Principal Amount]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T60">
								<Obj><![CDATA[     Verify  --> Decimal amount]]></Obj>
								<Details><![CDATA[Actual=00 ; Expected=00]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:50]]></Time>
								<NodeArgs eType="User" icon="6" nRep="315" status="Passed">
									<Disp><![CDATA[     Verify  --> Decimal amount]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T61">
								<Obj><![CDATA[     Verify  --> Remittance info 1]]></Obj>
								<Details><![CDATA[Actual=link rem info1 ; Expected=link rem info1]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:50]]></Time>
								<NodeArgs eType="User" icon="6" nRep="316" status="Passed">
									<Disp><![CDATA[     Verify  --> Remittance info 1]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T62">
								<Obj><![CDATA[     Verify  --> Remittance info 2]]></Obj>
								<Details><![CDATA[Actual=link rem info2 ; Expected=link rem info2]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:51]]></Time>
								<NodeArgs eType="User" icon="6" nRep="317" status="Passed">
									<Disp><![CDATA[     Verify  --> Remittance info 2]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T63">
								<Obj><![CDATA[     Verify  --> Remittance info 3]]></Obj>
								<Details><![CDATA[Actual=link rem info3 ; Expected=link rem info3]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:51]]></Time>
								<NodeArgs eType="User" icon="6" nRep="318" status="Passed">
									<Disp><![CDATA[     Verify  --> Remittance info 3]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T64">
								<Obj><![CDATA[     Verify  --> Remittance info 4]]></Obj>
								<Details><![CDATA[Actual=link rem info4 ; Expected=link rem info4]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:51]]></Time>
								<NodeArgs eType="User" icon="6" nRep="319" status="Passed">
									<Disp><![CDATA[     Verify  --> Remittance info 4]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T65">
								<Obj><![CDATA[     Verify  --> End to end identifier]]></Obj>
								<Details><![CDATA[Actual=200911161742190099ISABEL ; Expected=200911161742190099ISABEL]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:51]]></Time>
								<NodeArgs eType="User" icon="6" nRep="320" status="Passed">
									<Disp><![CDATA[     Verify  --> End to end identifier]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T66">
								<Obj><![CDATA[     Verify  --> RadioButton new/existing/own benef]]></Obj>
								<Details><![CDATA[Actual=CODE_BENEF ; Expected=CODE_BENEF]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:51]]></Time>
								<NodeArgs eType="User" icon="6" nRep="321" status="Passed">
									<Disp><![CDATA[     Verify  --> RadioButton new/existing/own benef]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T67">
								<Obj><![CDATA[     Verify  --> Benef account number]]></Obj>
								<Details><![CDATA[Actual=BE06 1351 1100 1522 ; Expected=BE06 1351 1100 1522]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:51]]></Time>
								<NodeArgs eType="User" icon="6" nRep="322" status="Passed">
									<Disp><![CDATA[     Verify  --> Benef account number]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T68">
								<Obj><![CDATA[     Verify  --> Benef alias]]></Obj>
								<Details><![CDATA[Actual=SEPA test 1 ; Expected=SEPA test 1]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:51]]></Time>
								<NodeArgs eType="User" icon="6" nRep="323" status="Passed">
									<Disp><![CDATA[     Verify  --> Benef alias]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T69">
								<Obj><![CDATA[     Verify  --> Benef BIC]]></Obj>
								<Details><![CDATA[Actual=ABERBE21 ; Expected=ABERBE21]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:51]]></Time>
								<NodeArgs eType="User" icon="6" nRep="324" status="Passed">
									<Disp><![CDATA[     Verify  --> Benef BIC]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T70">
								<Obj><![CDATA[     Verify  --> Benef name]]></Obj>
								<Details><![CDATA[Actual=SEPA test 1 ; Expected=SEPA test 1]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:52]]></Time>
								<NodeArgs eType="User" icon="6" nRep="325" status="Passed">
									<Disp><![CDATA[     Verify  --> Benef name]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T71">
								<Obj><![CDATA[     Verify  --> Payment name]]></Obj>
								<Details><![CDATA[Actual=EBANK-BUILDXP_20091116174225_1 ; Expected=EBANK-BUILDXP_20091116174225_1]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:52]]></Time>
								<NodeArgs eType="User" icon="6" nRep="330" status="Passed">
									<Disp><![CDATA[     Verify  --> Payment name]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T72">
								<Obj><![CDATA[     Verify  --> Shared Flag]]></Obj>
								<Details><![CDATA[Actual=0 ; Expected=0]]></Details>
								<Time><![CDATA[16/11/2009 - 17:42:52]]></Time>
								<NodeArgs eType="User" icon="6" nRep="331" status="Passed">
									<Disp><![CDATA[     Verify  --> Shared Flag]]></Disp>
								</NodeArgs>
							</Step>
							<Action rID="T73">
								<AName><![CDATA[aCancelSepaPayment]]></AName>
								<Step rID="T74">
									<Obj><![CDATA[Cancel payment]]></Obj>
									<Details><![CDATA[Blue error bar appeared, so cancel the payment and restart the encoding.]]></Details>
									<Time><![CDATA[16/11/2009 - 17:42:52]]></Time>
									<NodeArgs eType="User" icon="6" nRep="333">
										<Disp><![CDATA[Cancel payment]]></Disp>
									</NodeArgs>
								</Step>
								<Summary sTime="16/11/2009 - 17:42:52" eTime="16/11/2009 - 17:42:53" passed="0" failed="0" warnings="0"></Summary>
								<NodeArgs eType="StartAction" icon="7" nRep="332">
									<Disp><![CDATA[aCancelSepaPayment Summary]]></Disp>
								</NodeArgs>
							</Action>
							<Summary sTime="16/11/2009 - 17:42:42" eTime="16/11/2009 - 17:42:56" passed="17" failed="0" warnings="0"></Summary>
							<NodeArgs eType="StartAction" icon="7" nRep="298" status="Passed">
								<Disp><![CDATA[aModifySepaPayment Summary]]></Disp>
							</NodeArgs>
						</Action>
						<NodeArgs eType="StartIteration" icon="3" nRep="128" status="Passed">
							<Disp><![CDATA[StartEncodeSepa Iteration 1 (Row 1)]]></Disp>
						</NodeArgs>
					</AIter>
					<AIter rID="T75" iterID="2">
						<Step rID="T76">
							<Obj><![CDATA[Test : click sign button]]></Obj>