<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Romance Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="EBANK-BUILDXP"><DocLocation><![CDATA[Q:\SmokeTest\SmokeTest]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SmokeTest]]></DName>
<Res><![CDATA[Results]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Smoke]]></AName>
<Action rID="T5">
<AName><![CDATA[Prerequisites]]></AName>
<Summary sTime="25/06/2010 - 13:20:44" eTime="25/06/2010 - 13:20:49" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Prerequisites Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T6">
<AName><![CDATA[LogonIBS6]]></AName>
<Step rID="T7">
<Obj ><![CDATA[=== START ACTION : LogonIBS6 ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:20:49]]></Time>
<TimeTick>1277464849</TimeTick>
<NodeArgs eType="User" icon="5" nRep="11" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822" >
<Disp><![CDATA[=== START ACTION : LogonIBS6 ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[IBS6 was not yet open, so launch it...]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:20:55]]></Time>
<TimeTick>1277464855</TimeTick>
<NodeArgs eType="User" icon="5" nRep="14" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[IBS6 was not yet open, so launch it...]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[3 names were found in list of certificates]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:21:33]]></Time>
<TimeTick>1277464893</TimeTick>
<NodeArgs eType="User" icon="5" nRep="22" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[3 names were found in list of certificates]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[strData (certificate to select)=ClaudeCert]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:21:33]]></Time>
<TimeTick>1277464893</TimeTick>
<NodeArgs eType="User" icon="5" nRep="23" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[strData (certificate to select)=ClaudeCert]]></Disp>
</NodeArgs>
</Step>
<Action rID="T11">
<AName><![CDATA[SelectLogonProfile]]></AName>
<Step rID="T12">
<Obj ><![CDATA[LogonProfile2 found on portal.]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:22:02]]></Time>
<TimeTick>1277464922</TimeTick>
<NodeArgs eType="User" icon="5" nRep="65" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[LogonProfile2 found on portal.]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/06/2010 - 13:21:48" eTime="25/06/2010 - 13:22:10" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="34" status="Passed" >
<Disp><![CDATA[SelectLogonProfile Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="25/06/2010 - 13:20:49" eTime="25/06/2010 - 13:22:10" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[LogonIBS6 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[ViewExchangeRates]]></AName>
<Step rID="T14">
<Obj ><![CDATA[=== START ACTION : ViewExchangeRates ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:22:11]]></Time>
<TimeTick>1277464931</TimeTick>
<NodeArgs eType="User" icon="5" nRep="72" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822" >
<Disp><![CDATA[=== START ACTION : ViewExchangeRates ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[View exchange rate has been sorted]]></Obj>
<Details ><![CDATA[First line = 65,977200AFNAfghanistan Afghani01/02/07 2:00]]></Details>
<Time><![CDATA[25/06/2010 - 13:22:26]]></Time>
<TimeTick>1277464946</TimeTick>
<NodeArgs eType="User" icon="5" nRep="84" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[View exchange rate has been sorted]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/06/2010 - 13:22:11" eTime="25/06/2010 - 13:22:27" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="71" status="Passed" >
<Disp><![CDATA[ViewExchangeRates Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T16">
<AName><![CDATA[Preferences]]></AName>
<Step rID="T17">
<Obj ><![CDATA[=== START ACTION : Preferences ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:22:29]]></Time>
<TimeTick>1277464949</TimeTick>
<NodeArgs eType="User" icon="5" nRep="89" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822" >
<Disp><![CDATA[=== START ACTION : Preferences ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Separator field found]]></Obj>
<Details ><![CDATA[Tab 'General']]></Details>
<Time><![CDATA[25/06/2010 - 13:22:38]]></Time>
<TimeTick>1277464958</TimeTick>
<NodeArgs eType="User" icon="5" nRep="101" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Separator field found]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Default start-up folder is OK.]]></Obj>
<Details ><![CDATA[Tab 'General']]></Details>
<Time><![CDATA[25/06/2010 - 13:22:43]]></Time>
<TimeTick>1277464963</TimeTick>
<NodeArgs eType="User" icon="5" nRep="111" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Default start-up folder is OK.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Checkbox 'DownloadMerge' found]]></Obj>
<Details ><![CDATA[Tab 'Account info']]></Details>
<Time><![CDATA[25/06/2010 - 13:22:45]]></Time>
<TimeTick>1277464965</TimeTick>
<NodeArgs eType="User" icon="5" nRep="117" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Checkbox 'DownloadMerge' found]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[WebEdit 'DefaultViewOfAccountInfo_Pref' found]]></Obj>
<Details ><![CDATA[Tab 'Account info']]></Details>
<Time><![CDATA[25/06/2010 - 13:22:50]]></Time>
<TimeTick>1277464970</TimeTick>
<NodeArgs eType="User" icon="5" nRep="127" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[WebEdit 'DefaultViewOfAccountInfo_Pref' found]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[PrivateShared-list found.]]></Obj>
<Details ><![CDATA[Tab 'Transctions']]></Details>
<Time><![CDATA[25/06/2010 - 13:22:57]]></Time>
<TimeTick>1277464977</TimeTick>
<NodeArgs eType="User" icon="5" nRep="139" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[PrivateShared-list found.]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/06/2010 - 13:22:27" eTime="25/06/2010 - 13:22:58" passed="5" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="88" status="Passed" >
<Disp><![CDATA[Preferences Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T23">
<AName><![CDATA[DeleteTransactions]]></AName>
<Step rID="T24">
<Obj ><![CDATA[=== START ACTION : DeleteTransactions ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:23:00]]></Time>
<TimeTick>1277464980</TimeTick>
<NodeArgs eType="User" icon="5" nRep="146" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822" >
<Disp><![CDATA[=== START ACTION : DeleteTransactions ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Go to page 11]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:23:04]]></Time>
<TimeTick>1277464984</TimeTick>
<NodeArgs eType="User" icon="5" nRep="151" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Go to page 11]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[Confirmation to delete has appeared]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:23:11]]></Time>
<TimeTick>1277464991</TimeTick>
<NodeArgs eType="User" icon="5" nRep="164" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Confirmation to delete has appeared]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Go to page 11]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:23:14]]></Time>
<TimeTick>1277464994</TimeTick>
<NodeArgs eType="User" icon="5" nRep="168" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Go to page 11]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Confirmation to delete has appeared]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:23:21]]></Time>
<TimeTick>1277465001</TimeTick>
<NodeArgs eType="User" icon="5" nRep="181" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Confirmation to delete has appeared]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Transactions have been deleted]]></Obj>
<Details ><![CDATA[Number of pages : now = 10 , initial = 12]]></Details>
<Time><![CDATA[25/06/2010 - 13:23:25]]></Time>
<TimeTick>1277465005</TimeTick>
<NodeArgs eType="User" icon="5" nRep="185" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Transactions have been deleted]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/06/2010 - 13:22:58" eTime="25/06/2010 - 13:23:27" passed="5" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="145" status="Passed" >
<Disp><![CDATA[DeleteTransactions Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T30">
<AName><![CDATA[CreateCounterParty]]></AName>
<Step rID="T31">
<Obj ><![CDATA[=== START ACTION : CreateCounterParty ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:23:28]]></Time>
<TimeTick>1277465008</TimeTick>
<NodeArgs eType="User" icon="5" nRep="193" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822" >
<Disp><![CDATA[=== START ACTION : CreateCounterParty ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[IbanNumber 1 has been added]]></Obj>
<Details ><![CDATA[strIbamNumber = BE35 0630 2555 0037 ]]></Details>
<Time><![CDATA[25/06/2010 - 13:24:00]]></Time>
<TimeTick>1277465040</TimeTick>
<NodeArgs eType="User" icon="5" nRep="259" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[IbanNumber 1 has been added]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[IbanNumber 2 has been added]]></Obj>
<Details ><![CDATA[strIbamNumber = BE68 5390 0754 7034 ]]></Details>
<Time><![CDATA[25/06/2010 - 13:24:16]]></Time>
<TimeTick>1277465056</TimeTick>
<NodeArgs eType="User" icon="5" nRep="287" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[IbanNumber 2 has been added]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[DirectDebitNumber has been added]]></Obj>
<Details ><![CDATA[DirectDebitNumber = 000-0000100-03]]></Details>
<Time><![CDATA[25/06/2010 - 13:24:30]]></Time>
<TimeTick>1277465070</TimeTick>
<NodeArgs eType="User" icon="5" nRep="345" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[DirectDebitNumber has been added]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[IbanNumber1 has been replaced by IbanNumberModify (edit-mode)]]></Obj>
<Details ><![CDATA[strIbamNumberMod = BE21 7765 9112 8003  ,  IbamNumber1 = BE35 0630 2555 0037 ]]></Details>
<Time><![CDATA[25/06/2010 - 13:24:58]]></Time>
<TimeTick>1277465098</TimeTick>
<NodeArgs eType="User" icon="5" nRep="442" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[IbanNumber1 has been replaced by IbanNumberModify (edit-mode)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[Counterparty has been created/found]]></Obj>
<Details ><![CDATA['0 Alias 25062010132338' found.]]></Details>
<Time><![CDATA[25/06/2010 - 13:25:06]]></Time>
<TimeTick>1277465106</TimeTick>
<NodeArgs eType="User" icon="5" nRep="450" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Counterparty has been created/found]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[Modified CounterpartyName has been created/found]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:25:15]]></Time>
<TimeTick>1277465115</TimeTick>
<NodeArgs eType="User" icon="5" nRep="463" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Modified CounterpartyName has been created/found]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[IbanNumber 1 has been added]]></Obj>
<Details ><![CDATA[strIbamNumber = FR59 2004 1010 0405 6187 8A02 585 ]]></Details>
<Time><![CDATA[25/06/2010 - 13:25:48]]></Time>
<TimeTick>1277465148</TimeTick>
<NodeArgs eType="User" icon="5" nRep="524" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[IbanNumber 1 has been added]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[Counterparty has been created/found]]></Obj>
<Details ><![CDATA['0 Alias 25062010132518' found.]]></Details>
<Time><![CDATA[25/06/2010 - 13:25:55]]></Time>
<TimeTick>1277465155</TimeTick>
<NodeArgs eType="User" icon="5" nRep="533" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Counterparty has been created/found]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[Modified CounterpartyName has been created/found]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:26:04]]></Time>
<TimeTick>1277465164</TimeTick>
<NodeArgs eType="User" icon="5" nRep="546" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Modified CounterpartyName has been created/found]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/06/2010 - 13:23:28" eTime="25/06/2010 - 13:26:04" passed="9" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="192" status="Passed" >
<Disp><![CDATA[CreateCounterParty Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T41">
<AName><![CDATA[ManageCreditor]]></AName>
<Step rID="T42">
<Obj ><![CDATA[=== START ACTION : ManageCreditor ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:26:05]]></Time>
<TimeTick>1277465165</TimeTick>
<NodeArgs eType="User" icon="5" nRep="551" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822" >
<Disp><![CDATA[=== START ACTION : ManageCreditor ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[Creditor number has been deleted]]></Obj>
<Details ><![CDATA[Creditor number with text = .*123-456-749.* has been deleted.]]></Details>
<Time><![CDATA[25/06/2010 - 13:26:27]]></Time>
<TimeTick>1277465187</TimeTick>
<NodeArgs eType="User" icon="5" nRep="604" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Creditor number has been deleted]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Table (account) with text = CR_926_001515 has been selected]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:26:41]]></Time>
<TimeTick>1277465201</TimeTick>
<NodeArgs eType="User" icon="5" nRep="618" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Table (account) with text = CR_926_001515 has been selected]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Table (account) with text = 000-0000002-02 has been selected]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:26:42]]></Time>
<TimeTick>1277465202</TimeTick>
<NodeArgs eType="User" icon="5" nRep="623" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Table (account) with text = 000-0000002-02 has been selected]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[Creditor number has been created]]></Obj>
<Details ><![CDATA[Creditor number has as text = .*123-456-749.*]]></Details>
<Time><![CDATA[25/06/2010 - 13:26:46]]></Time>
<TimeTick>1277465206</TimeTick>
<NodeArgs eType="User" icon="5" nRep="627" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Creditor number has been created]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/06/2010 - 13:26:05" eTime="25/06/2010 - 13:26:50" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="550" status="Passed" >
<Disp><![CDATA[ManageCreditor Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T47">
<AName><![CDATA[EncodeDomesticPayment]]></AName>
<Step rID="T48">
<Obj ><![CDATA[=== START ACTION : EncodeDomesticPayment ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:26:50]]></Time>
<TimeTick>1277465210</TimeTick>
<NodeArgs eType="User" icon="5" nRep="634" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822" >
<Disp><![CDATA[=== START ACTION : EncodeDomesticPayment ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[The link 'Domestic payment' has been found and has been clicked on.]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:26:56]]></Time>
<TimeTick>1277465216</TimeTick>
<NodeArgs eType="User" icon="5" nRep="641" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[The link 'Domestic payment' has been found and has been clicked on.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[QTT was automatically filled in.]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:27:15]]></Time>
<TimeTick>1277465235</TimeTick>
<NodeArgs eType="User" icon="5" nRep="682" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[QTT was automatically filled in.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[QTT was automatically filled in.]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:27:31]]></Time>
<TimeTick>1277465251</TimeTick>
<NodeArgs eType="User" icon="5" nRep="721" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[QTT was automatically filled in.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[2 transactions  have been selected and will be grouped now.]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:27:47]]></Time>
<TimeTick>1277465267</TimeTick>
<NodeArgs eType="User" icon="5" nRep="739" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[2 transactions  have been selected and will be grouped now.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA['View details' appeared for : Payment group: 25062010132747]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[25/06/2010 - 13:28:08]]></Time>
<TimeTick>1277465288</TimeTick>
<NodeArgs eType="User" icon="5" nRep="762" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="138" >
<Disp><![CDATA['View details' appeared for : Payment group: 25062010132747]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA['View details' appeared for : Payment group: 25062010132747_clone]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[25/06/2010 - 13:28:20]]></Time>
<TimeTick>1277465300</TimeTick>
<NodeArgs eType="User" icon="5" nRep="780" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="138" >
<Disp><![CDATA['View details' appeared for : Payment group: 25062010132747_clone]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Isabel_IBS6]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[25/06/2010 - 13:28:29]]></Time>
<TimeTick>1277465309</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[IBS6]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/06/2010 - 13:28:29]]></Time>
<TimeTick>1277465309</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[TableRowTransaction.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2010 - 13:28:29]]></Time>
<TimeTick>1277465309</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="795" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="347" >
<Disp><![CDATA[TableRowTransaction.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[Counterparty has been saved]]></Obj>
<Details ><![CDATA[Counterparty  '25062010132722' has been saved.]]></Details>
<Time><![CDATA[25/06/2010 - 13:28:29]]></Time>
<TimeTick>1277465309</TimeTick>
<NodeArgs eType="User" icon="5" nRep="796" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="348" >
<Disp><![CDATA[Counterparty has been saved]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="794" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="347" >
<Disp><![CDATA[IBS6]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="793" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="347" >
<Disp><![CDATA[Isabel_IBS6]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/06/2010 - 13:26:50" eTime="25/06/2010 - 13:28:32" passed="7" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="633" status="Passed" >
<Disp><![CDATA[EncodeDomesticPayment Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T59">
<AName><![CDATA[DirectDebit]]></AName>
<Step rID="T60">
<Obj ><![CDATA[=== START ACTION : DirectDebit ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:28:33]]></Time>
<TimeTick>1277465313</TimeTick>
<NodeArgs eType="User" icon="5" nRep="804" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822" >
<Disp><![CDATA[=== START ACTION : DirectDebit ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA['View details' appeared for : DirectDebitGroupName 25062010132833]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[25/06/2010 - 13:30:27]]></Time>
<TimeTick>1277465427</TimeTick>
<NodeArgs eType="User" icon="5" nRep="922" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="138" >
<Disp><![CDATA['View details' appeared for : DirectDebitGroupName 25062010132833]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = insufficient. Actual status = Insufficiently signed]]></Details>
<Time><![CDATA[25/06/2010 - 13:30:27]]></Time>
<TimeTick>1277465427</TimeTick>
<NodeArgs eType="User" icon="5" nRep="925" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="326" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[Direct Debit has been added to group.]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:30:53]]></Time>
<TimeTick>1277465453</TimeTick>
<NodeArgs eType="User" icon="5" nRep="952" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Direct Debit has been added to group.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA[Direct Debit has been modified.]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2010 - 13:31:07]]></Time>
<TimeTick>1277465467</TimeTick>
<NodeArgs eType="User" icon="5" nRep="973" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[Direct Debit has been modified.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = not signed yet. Actual status = Not signed yet]]></Details>
<Time><![CDATA[25/06/2010 - 13:31:10]]></Time>
<TimeTick>1277465470</TimeTick>
<NodeArgs eType="User" icon="5" nRep="978" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="326" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = sufficiently. Actual status = Sufficiently signed]]></Details>
<Time><![CDATA[25/06/2010 - 13:31:25]]></Time>
<TimeTick>1277465485</TimeTick>
<NodeArgs eType="User" icon="5" nRep="990" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="326" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Isabel_IBS6]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[25/06/2010 - 13:31:36]]></Time>
<TimeTick>1277465496</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[IBS6]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/06/2010 - 13:31:36]]></Time>
<TimeTick>1277465496</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[TableRowTransaction.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2010 - 13:31:36]]></Time>
<TimeTick>1277465496</TimeTick>