<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Romance Standard Time">
	<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="EBANK-BUILDXP">
		<DocLocation><![CDATA[Q:\SmokeTest\SmokeTest]]></DocLocation>
	</General>
	<Doc rID="T1" productName="QuickTest Professional">
		<DName><![CDATA[SmokeTest]]></DName>
		<Res><![CDATA[53]]></Res>
		<DT rID="T2">
			<NodeArgs eType="Table" icon="2" nRep="4" filter="False">
				<Disp><![CDATA[Run-Time Data Table]]></Disp>
				<BtmPane vType="Table">
					<Path><![CDATA[Default.xls]]></Path>
				</BtmPane>
			</NodeArgs>
		</DT>
		<DIter rID="T3" iterID="1">
			<Action rID="T4">
				<AName><![CDATA[Smoke]]></AName>
				<Action rID="T5">
					<AName><![CDATA[Prerequisites]]></AName>
					<Summary sTime="27/05/2010 - 16:16:13" eTime="27/05/2010 - 16:16:20" passed="0" failed="0" warnings="0"></Summary>
					<NodeArgs eType="StartAction" icon="4" nRep="8">
						<Disp><![CDATA[Prerequisites Summary]]></Disp>
					</NodeArgs>
				</Action>
				<Action rID="T6">
					<AName><![CDATA[LogonIBS6]]></AName>
					<Step rID="T7">
						<Obj><![CDATA[=== START ACTION : LogonIBS6 ===]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[27/05/2010 - 16:16:21]]></Time>
						<TimeTick>1274969781</TimeTick>
						<NodeArgs eType="User" icon="5" nRep="11" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822">
							<Disp><![CDATA[=== START ACTION : LogonIBS6 ===]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T8">
						<Obj plainTxt="False"><![CDATA[Isabel_IBS6]]></Obj>
						<Details plainTxt="False"><![CDATA[Browser]]></Details>
						<Time><![CDATA[27/05/2010 - 16:16:26]]></Time>
						<TimeTick>1274969786</TimeTick>
						<Step rID="T9">
							<Obj plainTxt="False"><![CDATA[Isabel_IBS6.Exist]]></Obj>
							<Details plainTxt="False"><![CDATA["Object does not exist"]]></Details>
							<Time><![CDATA[27/05/2010 - 16:16:26]]></Time>
							<TimeTick>1274969786</TimeTick>
							<NodeArgs eType="Replay" icon="6" nRep="14" Source="LogonIBS6" SourceLine="23">
								<Disp><![CDATA[Isabel_IBS6.Exist]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T10">
							<Obj><![CDATA[IBS6 was not yet open, so launch it...]]></Obj>
							<Details><![CDATA[]]>
							</Details>
							<Time><![CDATA[27/05/2010 - 16:16:26]]></Time>
							<TimeTick>1274969786</TimeTick>
							<NodeArgs eType="User" icon="5" nRep="15" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719">
								<Disp><![CDATA[IBS6 was not yet open, so launch it...]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T11">
							<Obj plainTxt="False"><![CDATA[SystemUtil]]></Obj>
							<Details plainTxt="False"><![CDATA[SystemUtil]]></Details>
							<Time><![CDATA[27/05/2010 - 16:16:31]]></Time>
							<TimeTick>1274969791</TimeTick>
							<Step rID="T12">
								<Obj plainTxt="False"><![CDATA[Run "C:\Program Files\Internet Explorer\IEXPLORE.EXE",1]]></Obj>
								<Details plainTxt="False"><![CDATA[Run "C:\Program Files\Internet Explorer\IEXPLORE.EXE",1]]></Details>
								<Time><![CDATA[27/05/2010 - 16:16:31]]></Time>
								<TimeTick>1274969791</TimeTick>
								<NodeArgs eType="Replay" icon="7" nRep="19" status="Passed" Source="LogonIBS6" SourceLine="30">
									<Disp><![CDATA[Run "C:\Program Files\Internet Explorer\IEXPLORE.EXE",1]]></Disp>
								</NodeArgs>
							</Step>
							<NodeArgs eType="Replay" icon="7" nRep="18" status="Passed" Source="LogonIBS6" SourceLine="30">
								<Disp><![CDATA[SystemUtil]]></Disp>
							</NodeArgs>
						</Step>
						<NodeArgs eType="Context" icon="6" nRep="13" status="Passed" Source="LogonIBS6" SourceLine="23">
							<Disp><![CDATA[Isabel_IBS6]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T13">
						<Obj plainTxt="False"><![CDATA[Choose a digital certificate]]></Obj>
						<Details plainTxt="False"><![CDATA[Dialog]]></Details>
						<Time><![CDATA[27/05/2010 - 16:16:48]]></Time>
						<TimeTick>1274969808</TimeTick>
						<Step rID="T14">
							<Obj plainTxt="False"><![CDATA[ListOfNames.Exist]]></Obj>
							<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
							<Time><![CDATA[27/05/2010 - 16:16:48]]></Time>
							<TimeTick>1274969808</TimeTick>
							<NodeArgs eType="Replay" icon="9" nRep="21" Source="LogonIBS6" SourceLine="35">
								<Disp><![CDATA[ListOfNames.Exist]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T15">
							<Obj plainTxt="False"><![CDATA[ListOfNames.GetItemsCount]]></Obj>
							<Details plainTxt="False"><![CDATA[]]>
							</Details>
							<Time><![CDATA[27/05/2010 - 16:16:48]]></Time>
							<TimeTick>1274969808</TimeTick>
							<NodeArgs eType="Replay" icon="9" nRep="23" Source="LogonIBS6" SourceLine="37">
								<Disp><![CDATA[ListOfNames.GetItemsCount]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T16">
							<Obj><![CDATA[2 names were found in list of certificates]]></Obj>
							<Details><![CDATA[]]>
							</Details>
							<Time><![CDATA[27/05/2010 - 16:16:48]]></Time>
							<TimeTick>1274969808</TimeTick>
							<NodeArgs eType="User" icon="5" nRep="24" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719">
								<Disp><![CDATA[2 names were found in list of certificates]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T17">
							<Obj><![CDATA[strData (certificate to select)=ClaudeCert]]></Obj>
							<Details><![CDATA[]]>
							</Details>
							<Time><![CDATA[27/05/2010 - 16:16:48]]></Time>
							<TimeTick>1274969808</TimeTick>
							<NodeArgs eType="User" icon="5" nRep="25" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719">
								<Disp><![CDATA[strData (certificate to select)=ClaudeCert]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T18">
							<Obj plainTxt="False"><![CDATA[ListOfNames.Select]]></Obj>
							<Details plainTxt="False"><![CDATA[]]>
							</Details>
							<Time><![CDATA[27/05/2010 - 16:16:48]]></Time>
							<TimeTick>1274969808</TimeTick>
							<NodeArgs eType="Replay" icon="9" nRep="27" Source="LogonIBS6" SourceLine="40">
								<Disp><![CDATA[ListOfNames.Select]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T19">
							<Obj plainTxt="False"><![CDATA[OK.Click]]></Obj>
							<Details plainTxt="False"><![CDATA[]]>
							</Details>
							<Time><![CDATA[27/05/2010 - 16:16:48]]></Time>
							<TimeTick>1274969808</TimeTick>
							<NodeArgs eType="Replay" icon="10" nRep="29" Source="LogonIBS6" SourceLine="49">
								<Disp><![CDATA[OK.Click]]></Disp>
							</NodeArgs>
						</Step>
						<NodeArgs eType="Context" icon="8" nRep="20" status="Passed" Source="LogonIBS6" SourceLine="35">
							<Disp><![CDATA[Choose a digital certificate]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T20">
						<Obj plainTxt="False"><![CDATA[#32770]]></Obj>
						<Details plainTxt="False"><![CDATA[Dialog]]></Details>
						<Time><![CDATA[27/05/2010 - 16:16:49]]></Time>
						<TimeTick>1274969809</TimeTick>
						<Step rID="T21">
							<Obj plainTxt="False"><![CDATA[WinObject.Exist]]></Obj>
							<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
							<Time><![CDATA[27/05/2010 - 16:16:49]]></Time>
							<TimeTick>1274969809</TimeTick>
							<NodeArgs eType="Replay" icon="11" nRep="31" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="62">
								<Disp><![CDATA[WinObject.Exist]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T22">
							<Obj><![CDATA[IOS appeared after]]></Obj>
							<Details><![CDATA[1]]></Details>
							<Time><![CDATA[27/05/2010 - 16:16:49]]></Time>
							<TimeTick>1274969809</TimeTick>
							<NodeArgs eType="User" icon="5" nRep="32" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="64">
								<Disp><![CDATA[IOS appeared after]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T23">
							<Obj plainTxt="False"><![CDATA[WinObject.Type]]></Obj>
							<Details plainTxt="False"><![CDATA["isabel"]]></Details>
							<Time><![CDATA[27/05/2010 - 16:16:49]]></Time>
							<TimeTick>1274969809</TimeTick>
							<NodeArgs eType="Replay" icon="11" nRep="34" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="65">
								<Disp><![CDATA[WinObject.Type]]></Disp>
							</NodeArgs>
						</Step>
						<Step rID="T24">
							<Obj plainTxt="False"><![CDATA[#32770.Type]]></Obj>
							<Details plainTxt="False"><![CDATA["&lt__MicReturn&gt"]]></Details>
							<Time><![CDATA[27/05/2010 - 16:16:51]]></Time>
							<TimeTick>1274969811</TimeTick>
							<NodeArgs eType="Replay" icon="8" nRep="36" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="67">
								<Disp><![CDATA[#32770.Type]]></Disp>
							</NodeArgs>
						</Step>
						<NodeArgs eType="Context" icon="8" nRep="30" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="62">
							<Disp><![CDATA[#32770]]></Disp>
						</NodeArgs>
					</Step>
					<Action rID="T25">
						<AName><![CDATA[SelectLogonProfile]]></AName>
						<Step rID="T26">
							<Obj plainTxt="False"><![CDATA[Isabel_IBS6]]></Obj>
							<Details plainTxt="False"><![CDATA[Browser]]></Details>
							<Time><![CDATA[27/05/2010 - 16:17:02]]></Time>
							<TimeTick>1274969822</TimeTick>
							<Step rID="T27">
								<Obj plainTxt="False"><![CDATA[IBS6]]></Obj>
								<Details plainTxt="False"><![CDATA[Page]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:02]]></Time>
								<TimeTick>1274969822</TimeTick>
								<Step rID="T28">
									<Obj plainTxt="False"><![CDATA[BankItLogoPortal.Exist]]></Obj>
									<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
									<Time><![CDATA[27/05/2010 - 16:17:02]]></Time>
									<TimeTick>1274969822</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="41" Source="SelectLogonProfile" SourceLine="15">
										<Disp><![CDATA[BankItLogoPortal.Exist]]></Disp>
									</NodeArgs>
								</Step>
								<Step rID="T29">
									<Obj plainTxt="False"><![CDATA[LogonProfile1.Exist]]></Obj>
									<Details plainTxt="False"><![CDATA["Object does not exist"]]></Details>
									<Time><![CDATA[27/05/2010 - 16:17:13]]></Time>
									<TimeTick>1274969833</TimeTick>
									<NodeArgs eType="Replay" icon="14" nRep="72" Source="SelectLogonProfile" SourceLine="16">
										<Disp><![CDATA[LogonProfile1.Exist]]></Disp>
									</NodeArgs>
								</Step>
								<Step rID="T30">
									<Obj plainTxt="False"><![CDATA[LogonProfile2.Click]]></Obj>
									<Details plainTxt="False"><![CDATA[]]>
									</Details>
									<Time><![CDATA[27/05/2010 - 16:17:13]]></Time>
									<TimeTick>1274969833</TimeTick>
									<NodeArgs eType="Replay" icon="14" nRep="74" Source="SelectLogonProfile" SourceLine="20">
										<Disp><![CDATA[LogonProfile2.Click]]></Disp>
									</NodeArgs>
								</Step>
								<Step rID="T31">
									<Obj><![CDATA[LogonProfile2 found on portal.]]></Obj>
									<Details><![CDATA[]]>
									</Details>
									<Time><![CDATA[27/05/2010 - 16:17:14]]></Time>
									<TimeTick>1274969834</TimeTick>
									<NodeArgs eType="User" icon="5" nRep="75" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719">
										<Disp><![CDATA[LogonProfile2 found on portal.]]></Disp>
									</NodeArgs>
								</Step>
								<Step rID="T32">
									<Obj plainTxt="False"><![CDATA[TableRowTransaction.Exist]]></Obj>
									<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
									<Time><![CDATA[27/05/2010 - 16:17:19]]></Time>
									<TimeTick>1274969839</TimeTick>
									<NodeArgs eType="Replay" icon="15" nRep="77" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="181">
										<Disp><![CDATA[TableRowTransaction.Exist]]></Disp>
									</NodeArgs>
								</Step>
								<Step rID="T33">
									<Obj><![CDATA[Text of table row = ]]></Obj>
									<Details><![CDATA[ Uploaded payment file: stg_instdamt10euro_dbtrccyblank.xml110,00 EURSTG01/03/0927/05/10 15:16]]></Details>
									<Time><![CDATA[27/05/2010 - 16:17:19]]></Time>
									<TimeTick>1274969839</TimeTick>
									<NodeArgs eType="User" icon="5" nRep="78" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="185">
										<Disp><![CDATA[Text of table row = ]]></Disp>
									</NodeArgs>
								</Step>
								<NodeArgs eType="Context" icon="12" nRep="40" status="Passed" Source="SelectLogonProfile" SourceLine="15">
									<Disp><![CDATA[IBS6]]></Disp>
								</NodeArgs>
							</Step>
							<NodeArgs eType="Context" icon="6" nRep="39" status="Passed" Source="SelectLogonProfile" SourceLine="15">
								<Disp><![CDATA[Isabel_IBS6]]></Disp>
							</NodeArgs>
						</Step>
						<Summary sTime="27/05/2010 - 16:17:01" eTime="27/05/2010 - 16:17:19" passed="1" failed="0" warnings="0"></Summary>
						<NodeArgs eType="StartAction" icon="4" nRep="37" status="Passed">
							<Disp><![CDATA[SelectLogonProfile Summary]]></Disp>
						</NodeArgs>
					</Action>
					<Summary sTime="27/05/2010 - 16:16:20" eTime="27/05/2010 - 16:17:20" passed="4" failed="0" warnings="0"></Summary>
					<NodeArgs eType="StartAction" icon="4" nRep="10" status="Passed">
						<Disp><![CDATA[LogonIBS6 Summary]]></Disp>
					</NodeArgs>
				</Action>
				<Action rID="T34">
					<AName><![CDATA[ViewExchangeRates]]></AName>
					<Step rID="T35">
						<Obj><![CDATA[=== START ACTION : ViewExchangeRates ===]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[27/05/2010 - 16:17:20]]></Time>
						<TimeTick>1274969840</TimeTick>
						<NodeArgs eType="User" icon="5" nRep="82" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822">
							<Disp><![CDATA[=== START ACTION : ViewExchangeRates ===]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T36">
						<Obj plainTxt="False"><![CDATA[Isabel_IBS6]]></Obj>
						<Details plainTxt="False"><![CDATA[Browser]]></Details>
						<Time><![CDATA[27/05/2010 - 16:17:21]]></Time>
						<TimeTick>1274969841</TimeTick>
						<Step rID="T37">
							<Obj plainTxt="False"><![CDATA[IBS6]]></Obj>
							<Details plainTxt="False"><![CDATA[Page]]></Details>
							<Time><![CDATA[27/05/2010 - 16:17:21]]></Time>
							<TimeTick>1274969841</TimeTick>
							<Step rID="T38">
								<Obj plainTxt="False"><![CDATA[Tab_Transactions.Click]]></Obj>
								<Details plainTxt="False"><![CDATA[]]>
								</Details>
								<Time><![CDATA[27/05/2010 - 16:17:21]]></Time>
								<TimeTick>1274969841</TimeTick>
								<NodeArgs eType="Replay" icon="16" nRep="87" Source="ViewExchangeRates" SourceLine="5">
									<Disp><![CDATA[Tab_Transactions.Click]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T39">
								<Obj plainTxt="False"><![CDATA[TableRowTransaction.Exist]]></Obj>
								<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:23]]></Time>
								<TimeTick>1274969843</TimeTick>
								<NodeArgs eType="Replay" icon="15" nRep="89" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="181">
									<Disp><![CDATA[TableRowTransaction.Exist]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T40">
								<Obj><![CDATA[Text of table row = ]]></Obj>
								<Details><![CDATA[ Uploaded payment file: stg_instdamt10euro_dbtrccyblank.xml110,00 EURSTG01/03/0927/05/10 15:16]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:23]]></Time>
								<TimeTick>1274969843</TimeTick>
								<NodeArgs eType="User" icon="5" nRep="90" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="185">
									<Disp><![CDATA[Text of table row = ]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T41">
								<Obj plainTxt="False"><![CDATA[ViewExchangeRates_LinkMainMenu.Click]]></Obj>
								<Details plainTxt="False"><![CDATA[]]>
								</Details>
								<Time><![CDATA[27/05/2010 - 16:17:25]]></Time>
								<TimeTick>1274969845</TimeTick>
								<NodeArgs eType="Replay" icon="16" nRep="92" Source="ViewExchangeRates" SourceLine="8">
									<Disp><![CDATA[ViewExchangeRates_LinkMainMenu.Click]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T42">
								<Obj plainTxt="False"><![CDATA[TargetCurrency_ViewXRates.Exist]]></Obj>
								<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:27]]></Time>
								<TimeTick>1274969847</TimeTick>
								<NodeArgs eType="Replay" icon="14" nRep="93" Source="ViewExchangeRates" SourceLine="9">
									<Disp><![CDATA[TargetCurrency_ViewXRates.Exist]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T43">
								<Obj plainTxt="False"><![CDATA[TargetCurrency_ViewXRates.Click]]></Obj>
								<Details plainTxt="False"><![CDATA[]]>
								</Details>
								<Time><![CDATA[27/05/2010 - 16:17:30]]></Time>
								<TimeTick>1274969850</TimeTick>
								<NodeArgs eType="Replay" icon="14" nRep="95" Source="ViewExchangeRates" SourceLine="11">
									<Disp><![CDATA[TargetCurrency_ViewXRates.Click]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T44">
								<Obj><![CDATA[View exchange rate has been sorted]]></Obj>
								<Details><![CDATA[First line = 65,977200AFNAfghanistan Afghani01/02/07 2:00]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:32]]></Time>
								<TimeTick>1274969852</TimeTick>
								<NodeArgs eType="User" icon="5" nRep="96" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719">
									<Disp><![CDATA[View exchange rate has been sorted]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T45">
								<Obj plainTxt="False"><![CDATA[Close_General.Click]]></Obj>
								<Details plainTxt="False"><![CDATA[]]>
								</Details>
								<Time><![CDATA[27/05/2010 - 16:17:33]]></Time>
								<TimeTick>1274969853</TimeTick>
								<NodeArgs eType="Replay" icon="17" nRep="98" Source="ViewExchangeRates" SourceLine="30">
									<Disp><![CDATA[Close_General.Click]]></Disp>
								</NodeArgs>
							</Step>
							<NodeArgs eType="Context" icon="12" nRep="86" status="Passed" Source="ViewExchangeRates" SourceLine="5">
								<Disp><![CDATA[IBS6]]></Disp>
							</NodeArgs>
						</Step>
						<NodeArgs eType="Context" icon="6" nRep="85" status="Passed" Source="ViewExchangeRates" SourceLine="5">
							<Disp><![CDATA[Isabel_IBS6]]></Disp>
						</NodeArgs>
					</Step>
					<Summary sTime="27/05/2010 - 16:17:20" eTime="27/05/2010 - 16:17:33" passed="1" failed="0" warnings="0"></Summary>
					<NodeArgs eType="StartAction" icon="4" nRep="81" status="Passed">
						<Disp><![CDATA[ViewExchangeRates Summary]]></Disp>
					</NodeArgs>
				</Action>
				<Action rID="T46">
					<AName><![CDATA[Preferences]]></AName>
					<Step rID="T47">
						<Obj><![CDATA[=== START ACTION : Preferences ===]]></Obj>
						<Details><![CDATA[]]>
						</Details>
						<Time><![CDATA[27/05/2010 - 16:17:35]]></Time>
						<TimeTick>1274969855</TimeTick>
						<NodeArgs eType="User" icon="5" nRep="101" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822">
							<Disp><![CDATA[=== START ACTION : Preferences ===]]></Disp>
						</NodeArgs>
					</Step>
					<Step rID="T48">
						<Obj plainTxt="False"><![CDATA[Isabel_IBS6]]></Obj>
						<Details plainTxt="False"><![CDATA[Browser]]></Details>
						<Time><![CDATA[27/05/2010 - 16:17:37]]></Time>
						<TimeTick>1274969857</TimeTick>
						<Step rID="T49">
							<Obj plainTxt="False"><![CDATA[IBS6]]></Obj>
							<Details plainTxt="False"><![CDATA[Page]]></Details>
							<Time><![CDATA[27/05/2010 - 16:17:37]]></Time>
							<TimeTick>1274969857</TimeTick>
							<Step rID="T50">
								<Obj plainTxt="False"><![CDATA[TableRowTransaction.Exist]]></Obj>
								<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:37]]></Time>
								<TimeTick>1274969857</TimeTick>
								<NodeArgs eType="Replay" icon="15" nRep="105" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="181">
									<Disp><![CDATA[TableRowTransaction.Exist]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T51">
								<Obj><![CDATA[Text of table row = ]]></Obj>
								<Details><![CDATA[ Uploaded payment file: stg_instdamt10euro_dbtrccyblank.xml110,00 EURSTG01/03/0927/05/10 15:16]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:37]]></Time>
								<TimeTick>1274969857</TimeTick>
								<NodeArgs eType="User" icon="5" nRep="106" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="185">
									<Disp><![CDATA[Text of table row = ]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T52">
								<Obj plainTxt="False"><![CDATA[Preferences_LinkMainMenu.Click]]></Obj>
								<Details plainTxt="False"><![CDATA[]]>
								</Details>
								<Time><![CDATA[27/05/2010 - 16:17:39]]></Time>
								<TimeTick>1274969859</TimeTick>
								<NodeArgs eType="Replay" icon="16" nRep="108" Source="Preferences" SourceLine="10">
									<Disp><![CDATA[Preferences_LinkMainMenu.Click]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T53">
								<Obj plainTxt="False"><![CDATA[General_Pref.Click]]></Obj>
								<Details plainTxt="False"><![CDATA[]]>
								</Details>
								<Time><![CDATA[27/05/2010 - 16:17:40]]></Time>
								<TimeTick>1274969860</TimeTick>
								<NodeArgs eType="Replay" icon="16" nRep="110" Source="Preferences" SourceLine="14">
									<Disp><![CDATA[General_Pref.Click]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T54">
								<Obj plainTxt="False"><![CDATA[csvSeparator_Pref.Exist]]></Obj>
								<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:41]]></Time>
								<TimeTick>1274969861</TimeTick>
								<NodeArgs eType="Replay" icon="18" nRep="111" Source="Preferences" SourceLine="15">
									<Disp><![CDATA[csvSeparator_Pref.Exist]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T55">
								<Obj plainTxt="False"><![CDATA[csvSeparator_Pref.Set]]></Obj>
								<Details plainTxt="False"><![CDATA["="]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:41]]></Time>
								<TimeTick>1274969861</TimeTick>
								<NodeArgs eType="Replay" icon="18" nRep="113" Source="Preferences" SourceLine="16">
									<Disp><![CDATA[csvSeparator_Pref.Set]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T56">
								<Obj><![CDATA[Separator field found]]></Obj>
								<Details><![CDATA[Tab 'General']]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:41]]></Time>
								<TimeTick>1274969861</TimeTick>
								<NodeArgs eType="User" icon="5" nRep="114" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719">
									<Disp><![CDATA[Separator field found]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T57">
								<Obj plainTxt="False"><![CDATA[DefaultStart-upFolder_Pref.Exist]]></Obj>
								<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:41]]></Time>
								<TimeTick>1274969861</TimeTick>
								<NodeArgs eType="Replay" icon="18" nRep="115" Source="Preferences" SourceLine="22">
									<Disp><![CDATA[DefaultStart-upFolder_Pref.Exist]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T58">
								<Obj plainTxt="False"><![CDATA[DefaultStart-upFolder_Pref.Exist]]></Obj>
								<Details plainTxt="False"><![CDATA["Object exists"]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:42]]></Time>
								<TimeTick>1274969862</TimeTick>
								<NodeArgs eType="Replay" icon="18" nRep="117" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="295">
									<Disp><![CDATA[DefaultStart-upFolder_Pref.Exist]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T59">
								<Obj plainTxt="False"><![CDATA[DefaultStart-upFolder_Pref.Click]]></Obj>
								<Details plainTxt="False"><![CDATA[]]>
								</Details>
								<Time><![CDATA[27/05/2010 - 16:17:42]]></Time>
								<TimeTick>1274969862</TimeTick>
								<NodeArgs eType="Replay" icon="18" nRep="119" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="296">
									<Disp><![CDATA[DefaultStart-upFolder_Pref.Click]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T60">
								<Obj plainTxt="False"><![CDATA[DefaultStart-upFolder_Pref.Set]]></Obj>
								<Details plainTxt="False"><![CDATA["Transactions"]]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:42]]></Time>
								<TimeTick>1274969862</TimeTick>
								<NodeArgs eType="Replay" icon="18" nRep="121" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="299">
									<Disp><![CDATA[DefaultStart-upFolder_Pref.Set]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T61">
								<Obj plainTxt="False"><![CDATA[DefaultStart-upFolder_Pref.Click]]></Obj>
								<Details plainTxt="False"><![CDATA[]]>
								</Details>
								<Time><![CDATA[27/05/2010 - 16:17:43]]></Time>
								<TimeTick>1274969863</TimeTick>
								<NodeArgs eType="Replay" icon="18" nRep="123" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="302">
									<Disp><![CDATA[DefaultStart-upFolder_Pref.Click]]></Disp>
								</NodeArgs>
							</Step>
							<Step rID="T62">
								<Obj><![CDATA[Default start-up folder is OK.]]></Obj>
								<Details><![CDATA[Tab 'General']]></Details>
								<Time><![CDATA[27/05/2010 - 16:17:46]]></Time>
								<TimeTick>1274969866</TimeTick>
								<NodeArgs eType="User" icon="5" nRep="124" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719">
									<Disp><![CDATA[Default start-up folder is OK.]]></Disp>
								</NodeArgs>
							</Step>