<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Romance Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="EBANK-BUILDXP"><DocLocation><![CDATA[Q:\SmokeTest\SmokeTest]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SmokeTest]]></DName>
<Res><![CDATA[Results]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Smoke]]></AName>
<Action rID="T5">
<AName><![CDATA[Prerequisites]]></AName>
<Summary sTime="2/06/2010 - 13:45:31" eTime="2/06/2010 - 13:45:32" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Prerequisites Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T6">
<AName><![CDATA[LogonIBS6]]></AName>
<Step rID="T7">
<Obj ><![CDATA[=== START ACTION : LogonIBS6 ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2/06/2010 - 13:45:33]]></Time>
<TimeTick>1275479133</TimeTick>
<NodeArgs eType="User" icon="5" nRep="11" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="822" >
<Disp><![CDATA[=== START ACTION : LogonIBS6 ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[IBS6 was not yet open, so launch it...]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2/06/2010 - 13:45:38]]></Time>
<TimeTick>1275479138</TimeTick>
<NodeArgs eType="User" icon="5" nRep="14" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[IBS6 was not yet open, so launch it...]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[2 names were found in list of certificates]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2/06/2010 - 13:46:11]]></Time>
<TimeTick>1275479171</TimeTick>
<NodeArgs eType="User" icon="5" nRep="22" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[2 names were found in list of certificates]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[strData (certificate to select)=ClaudeCert]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2/06/2010 - 13:46:11]]></Time>
<TimeTick>1275479171</TimeTick>
<NodeArgs eType="User" icon="5" nRep="23" status="Passed" Source="Q:\SmokeTest\SmokeTestFunctions.qfl" SourceLine="719" >
<Disp><![CDATA[strData (certificate to select)=ClaudeCert]]></Disp>
</NodeArgs>
</Step>
<Action rID="T11">
<AName><![CDATA[SelectLogonProfile]]></AName>
<Summary sTime="2/06/2010 - 13:46:26" eTime="2/06/2010 - 13:46:57" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="34" >
<Disp><![CDATA[SelectLogonProfile Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2/06/2010 - 13:45:32" eTime="2/06/2010 - 13:46:57" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[LogonIBS6 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2/06/2010 - 13:45:31" eTime="2/06/2010 - 13:46:57" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Smoke Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[SmokeTest Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2/06/2010 - 13:45:25" eTime="2/06/2010 - 13:46:57" passed="3" failed="0" warnings="0" stopped="True" ><Param ><ParamName><![CDATA[Env]]></ParamName><ParamVal><![CDATA[acc]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test SmokeTest Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>