<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Romance Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="EBANK-BUILD2XP7"><DocLocation><![CDATA[Q:/SmokeTest2.3/SmokeTest]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SmokeTest]]></DName>
<Res><![CDATA[Results]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Smoke]]></AName>
<Action rID="T5">
<AName><![CDATA[Prerequisites]]></AName>
<Summary sTime="5/16/2011 - 9:01:16" eTime="5/16/2011 - 9:01:16" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Prerequisites Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T6">
<AName><![CDATA[LogonIBS6]]></AName>
<Step rID="T7">
<Obj ><![CDATA[=== START ACTION : LogonIBS6 ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:01:17]]></Time>
<TimeTick>1305529277</TimeTick>
<NodeArgs eType="User" icon="5" nRep="11" >
<Disp><![CDATA[=== START ACTION : LogonIBS6 ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[IBS6 was not yet open, so launch it...]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:01:22]]></Time>
<TimeTick>1305529282</TimeTick>
<NodeArgs eType="User" icon="5" nRep="14" status="Passed" >
<Disp><![CDATA[IBS6 was not yet open, so launch it...]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[9 names were found in list of certificates]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:01:26]]></Time>
<TimeTick>1305529286</TimeTick>
<NodeArgs eType="User" icon="5" nRep="22" status="Passed" >
<Disp><![CDATA[9 names were found in list of certificates]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[strData (certificate to select)=ClaudeCert]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:01:26]]></Time>
<TimeTick>1305529286</TimeTick>
<NodeArgs eType="User" icon="5" nRep="23" status="Passed" >
<Disp><![CDATA[strData (certificate to select)=ClaudeCert]]></Disp>
</NodeArgs>
</Step>
<Action rID="T11">
<AName><![CDATA[SelectLogonProfile]]></AName>
<Step rID="T12">
<Obj ><![CDATA[LogonProfile2 found on portal.]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:01:46]]></Time>
<TimeTick>1305529306</TimeTick>
<NodeArgs eType="User" icon="5" nRep="70" status="Passed" >
<Disp><![CDATA[LogonProfile2 found on portal.]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/16/2011 - 9:01:39" eTime="5/16/2011 - 9:02:02" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="36" status="Passed" >
<Disp><![CDATA[SelectLogonProfile Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="5/16/2011 - 9:01:17" eTime="5/16/2011 - 9:02:02" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[LogonIBS6 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[Upload]]></AName>
<Step rID="T14">
<Obj ><![CDATA[=== START ACTION : Upload ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:02:02]]></Time>
<TimeTick>1305529322</TimeTick>
<NodeArgs eType="User" icon="5" nRep="114" >
<Disp><![CDATA[=== START ACTION : Upload ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA['View details' clicked for : divfile.txt]]></Obj>
<Details ><![CDATA[Click done.]]></Details>
<Time><![CDATA[5/16/2011 - 9:02:54]]></Time>
<TimeTick>1305529374</TimeTick>
<NodeArgs eType="User" icon="5" nRep="252" status="Passed" >
<Disp><![CDATA['View details' clicked for : divfile.txt]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA['View details' appeared for : divfile.txt]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[5/16/2011 - 9:02:56]]></Time>
<TimeTick>1305529376</TimeTick>
<NodeArgs eType="User" icon="5" nRep="254" status="Passed" >
<Disp><![CDATA['View details' appeared for : divfile.txt]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = not signed yet. Actual status = Not signed yet]]></Details>
<Time><![CDATA[5/16/2011 - 9:02:56]]></Time>
<TimeTick>1305529376</TimeTick>
<NodeArgs eType="User" icon="5" nRep="258" status="Passed" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[     Verify  --> Transaction type]]></Obj>
<Details ><![CDATA[Actual=STG Specific Format  ; Expected=STG Specific Format ]]></Details>
<Time><![CDATA[5/16/2011 - 9:02:56]]></Time>
<TimeTick>1305529376</TimeTick>
<NodeArgs eType="User" icon="5" nRep="264" status="Passed" >
<Disp><![CDATA[     Verify  --> Transaction type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[     Verify  --> File size]]></Obj>
<Details ><![CDATA[Actual=20 bytes  ; Expected=20 bytes ]]></Details>
<Time><![CDATA[5/16/2011 - 9:02:56]]></Time>
<TimeTick>1305529376</TimeTick>
<NodeArgs eType="User" icon="5" nRep="268" status="Passed" >
<Disp><![CDATA[     Verify  --> File size]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[     Verify  --> File format]]></Obj>
<Details ><![CDATA[Actual=Free format  ; Expected=Free format]]></Details>
<Time><![CDATA[5/16/2011 - 9:02:57]]></Time>
<TimeTick>1305529377</TimeTick>
<NodeArgs eType="User" icon="5" nRep="269" status="Passed" >
<Disp><![CDATA[     Verify  --> File format]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[NumberOfSignaturesRequired = 1]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:13]]></Time>
<TimeTick>1305529393</TimeTick>
<NodeArgs eType="User" icon="5" nRep="282" >
<Disp><![CDATA[NumberOfSignaturesRequired = 1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = sufficient. Actual status = Sufficiently signed]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:13]]></Time>
<TimeTick>1305529393</TimeTick>
<NodeArgs eType="User" icon="5" nRep="285" status="Passed" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA['View details' clicked for : fortis_acc_128.rca]]></Obj>
<Details ><![CDATA[Click done.]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:16]]></Time>
<TimeTick>1305529396</TimeTick>
<NodeArgs eType="User" icon="5" nRep="293" status="Passed" >
<Disp><![CDATA['View details' clicked for : fortis_acc_128.rca]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA['View details' appeared for : fortis_acc_128.rca]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:18]]></Time>
<TimeTick>1305529398</TimeTick>
<NodeArgs eType="User" icon="5" nRep="295" status="Passed" >
<Disp><![CDATA['View details' appeared for : fortis_acc_128.rca]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = not signed yet. Actual status = Not signed yet]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:18]]></Time>
<TimeTick>1305529398</TimeTick>
<NodeArgs eType="User" icon="5" nRep="299" status="Passed" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[     Verify  --> Transaction type]]></Obj>
<Details ><![CDATA[Actual=Belgian cheque  ; Expected=Belgian cheque ]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:18]]></Time>
<TimeTick>1305529398</TimeTick>
<NodeArgs eType="User" icon="5" nRep="305" status="Passed" >
<Disp><![CDATA[     Verify  --> Transaction type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[     Verify  --> File size]]></Obj>
<Details ><![CDATA[Actual=390 bytes  ; Expected=390 bytes]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:18]]></Time>
<TimeTick>1305529398</TimeTick>
<NodeArgs eType="User" icon="5" nRep="309" status="Passed" >
<Disp><![CDATA[     Verify  --> File size]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[     Verify  --> File format]]></Obj>
<Details ><![CDATA[Actual=CIRI RCA 128  ; Expected=CIRI RCA 128 ]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:18]]></Time>
<TimeTick>1305529398</TimeTick>
<NodeArgs eType="User" icon="5" nRep="310" status="Passed" >
<Disp><![CDATA[     Verify  --> File format]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[NumberOfSignaturesRequired = 1]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:32]]></Time>
<TimeTick>1305529412</TimeTick>
<NodeArgs eType="User" icon="5" nRep="323" >
<Disp><![CDATA[NumberOfSignaturesRequired = 1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = sufficient. Actual status = Sufficiently signed]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:32]]></Time>
<TimeTick>1305529412</TimeTick>
<NodeArgs eType="User" icon="5" nRep="326" status="Passed" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA['View details' clicked for : fortis_sepa.xml]]></Obj>
<Details ><![CDATA[Click done.]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:35]]></Time>
<TimeTick>1305529415</TimeTick>
<NodeArgs eType="User" icon="5" nRep="334" status="Passed" >
<Disp><![CDATA['View details' clicked for : fortis_sepa.xml]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA['View details' appeared for : fortis_sepa.xml]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:38]]></Time>
<TimeTick>1305529418</TimeTick>
<NodeArgs eType="User" icon="5" nRep="336" status="Passed" >
<Disp><![CDATA['View details' appeared for : fortis_sepa.xml]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = not signed yet. Actual status = Not signed yet]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:38]]></Time>
<TimeTick>1305529418</TimeTick>
<NodeArgs eType="User" icon="5" nRep="340" status="Passed" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[     Verify  --> Transaction type]]></Obj>
<Details ><![CDATA[Actual=SEPA payment  ; Expected=SEPA payment ]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:38]]></Time>
<TimeTick>1305529418</TimeTick>
<NodeArgs eType="User" icon="5" nRep="346" status="Passed" >
<Disp><![CDATA[     Verify  --> Transaction type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[     Verify  --> File size]]></Obj>
<Details ><![CDATA[Actual=1089 bytes  ; Expected=1089 bytes ]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:38]]></Time>
<TimeTick>1305529418</TimeTick>
<NodeArgs eType="User" icon="5" nRep="350" status="Passed" >
<Disp><![CDATA[     Verify  --> File size]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[     Verify  --> File format]]></Obj>
<Details ><![CDATA[Actual=XML-CT pain.001.001.02  ; Expected=XML-CT pain.001.001.02]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:38]]></Time>
<TimeTick>1305529418</TimeTick>
<NodeArgs eType="User" icon="5" nRep="351" status="Passed" >
<Disp><![CDATA[     Verify  --> File format]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[     Verify  --> Reason of payment]]></Obj>
<Details ><![CDATA[Actual=SEPA ordinary transfer  ; Expected=SEPA ordinary transfer ]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:38]]></Time>
<TimeTick>1305529418</TimeTick>
<NodeArgs eType="User" icon="5" nRep="352" status="Passed" >
<Disp><![CDATA[     Verify  --> Reason of payment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[     Verify  --> Global/single debit]]></Obj>
<Details ><![CDATA[Actual=Single debit ; Expected=Single debit]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:38]]></Time>
<TimeTick>1305529418</TimeTick>
<NodeArgs eType="User" icon="5" nRep="360" status="Passed" >
<Disp><![CDATA[     Verify  --> Global/single debit]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = sufficient. Actual status = Sufficiently signed]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:52]]></Time>
<TimeTick>1305529432</TimeTick>
<NodeArgs eType="User" icon="5" nRep="374" status="Passed" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA['View details' clicked for : stg 128.fbf]]></Obj>
<Details ><![CDATA[Click done.]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:55]]></Time>
<TimeTick>1305529435</TimeTick>
<NodeArgs eType="User" icon="5" nRep="382" status="Passed" >
<Disp><![CDATA['View details' clicked for : stg 128.fbf]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA['View details' appeared for : stg 128.fbf]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:57]]></Time>
<TimeTick>1305529437</TimeTick>
<NodeArgs eType="User" icon="5" nRep="384" status="Passed" >
<Disp><![CDATA['View details' appeared for : stg 128.fbf]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = not signed yet. Actual status = Not signed yet]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:57]]></Time>
<TimeTick>1305529437</TimeTick>
<NodeArgs eType="User" icon="5" nRep="388" status="Passed" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[     Verify  --> Transaction type]]></Obj>
<Details ><![CDATA[Actual=Belgian domestic payment  ; Expected=Belgian domestic payment ]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:58]]></Time>
<TimeTick>1305529438</TimeTick>
<NodeArgs eType="User" icon="5" nRep="394" status="Passed" >
<Disp><![CDATA[     Verify  --> Transaction type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[     Verify  --> File size]]></Obj>
<Details ><![CDATA[Actual=520 bytes  ; Expected=520 bytes ]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:58]]></Time>
<TimeTick>1305529438</TimeTick>
<NodeArgs eType="User" icon="5" nRep="398" status="Passed" >
<Disp><![CDATA[     Verify  --> File size]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[     Verify  --> File format]]></Obj>
<Details ><![CDATA[Actual=CIRI FBF 128  ; Expected=CIRI FBF 128]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:58]]></Time>
<TimeTick>1305529438</TimeTick>
<NodeArgs eType="User" icon="5" nRep="399" status="Passed" >
<Disp><![CDATA[     Verify  --> File format]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[     Verify  --> Reason of payment]]></Obj>
<Details ><![CDATA[Actual=00 Ordinary transfer  ; Expected=00 Ordinary transfer ]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:58]]></Time>
<TimeTick>1305529438</TimeTick>
<NodeArgs eType="User" icon="5" nRep="400" status="Passed" >
<Disp><![CDATA[     Verify  --> Reason of payment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[     Verify  --> Global/single debit]]></Obj>
<Details ><![CDATA[Actual=Single debit ; Expected=Single debit]]></Details>
<Time><![CDATA[5/16/2011 - 9:03:58]]></Time>
<TimeTick>1305529438</TimeTick>
<NodeArgs eType="User" icon="5" nRep="408" status="Passed" >
<Disp><![CDATA[     Verify  --> Global/single debit]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA['View details' clicked for : stg_128_20payments_nonglobal.fbf]]></Obj>
<Details ><![CDATA[Click done.]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:01]]></Time>
<TimeTick>1305529441</TimeTick>
<NodeArgs eType="User" icon="5" nRep="416" status="Passed" >
<Disp><![CDATA['View details' clicked for : stg_128_20payments_nonglobal.fbf]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA['View details' appeared for : stg_128_20payments_nonglobal.fbf]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:04]]></Time>
<TimeTick>1305529444</TimeTick>
<NodeArgs eType="User" icon="5" nRep="418" status="Passed" >
<Disp><![CDATA['View details' appeared for : stg_128_20payments_nonglobal.fbf]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = not signed yet. Actual status = Not signed yet]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:04]]></Time>
<TimeTick>1305529444</TimeTick>
<NodeArgs eType="User" icon="5" nRep="422" status="Passed" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[     Verify  --> Transaction type]]></Obj>
<Details ><![CDATA[Actual=Belgian domestic payment  ; Expected=Belgian domestic payment ]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:04]]></Time>
<TimeTick>1305529444</TimeTick>
<NodeArgs eType="User" icon="5" nRep="428" status="Passed" >
<Disp><![CDATA[     Verify  --> Transaction type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[     Verify  --> File size]]></Obj>
<Details ><![CDATA[Actual=10400 bytes  ; Expected=10400 bytes ]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:04]]></Time>
<TimeTick>1305529444</TimeTick>
<NodeArgs eType="User" icon="5" nRep="432" status="Passed" >
<Disp><![CDATA[     Verify  --> File size]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[     Verify  --> File format]]></Obj>
<Details ><![CDATA[Actual=CIRI FBF 128  ; Expected=CIRI FBF 128]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:04]]></Time>
<TimeTick>1305529444</TimeTick>
<NodeArgs eType="User" icon="5" nRep="433" status="Passed" >
<Disp><![CDATA[     Verify  --> File format]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[     Verify  --> Reason of payment]]></Obj>
<Details ><![CDATA[Actual=00 Ordinary transfer  ; Expected=00 Ordinary transfer ]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:04]]></Time>
<TimeTick>1305529444</TimeTick>
<NodeArgs eType="User" icon="5" nRep="434" status="Passed" >
<Disp><![CDATA[     Verify  --> Reason of payment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj ><![CDATA[     Verify  --> Global/single debit]]></Obj>
<Details ><![CDATA[Actual=Single debit ; Expected=Single debit]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:04]]></Time>
<TimeTick>1305529444</TimeTick>
<NodeArgs eType="User" icon="5" nRep="442" status="Passed" >
<Disp><![CDATA[     Verify  --> Global/single debit]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA['View details' clicked for : stg_0002000.dom]]></Obj>
<Details ><![CDATA[Click done.]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:08]]></Time>
<TimeTick>1305529448</TimeTick>
<NodeArgs eType="User" icon="5" nRep="450" status="Passed" >
<Disp><![CDATA['View details' clicked for : stg_0002000.dom]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA['View details' appeared for : stg_0002000.dom]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:10]]></Time>
<TimeTick>1305529450</TimeTick>
<NodeArgs eType="User" icon="5" nRep="452" status="Passed" >
<Disp><![CDATA['View details' appeared for : stg_0002000.dom]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[    Expected status is correct.]]></Obj>
<Details ><![CDATA[Expected status = not signed yet. Actual status = Not signed yet]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:10]]></Time>
<TimeTick>1305529450</TimeTick>
<NodeArgs eType="User" icon="5" nRep="456" status="Passed" >
<Disp><![CDATA[    Expected status is correct.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[     Verify  --> Transaction type]]></Obj>
<Details ><![CDATA[Actual=Belgian direct debit  ; Expected=Belgian direct debit ]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:10]]></Time>
<TimeTick>1305529450</TimeTick>
<NodeArgs eType="User" icon="5" nRep="462" status="Passed" >
<Disp><![CDATA[     Verify  --> Transaction type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[     Verify  --> File size]]></Obj>
<Details ><![CDATA[Actual=390 bytes  ; Expected=390 bytes ]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:10]]></Time>
<TimeTick>1305529450</TimeTick>
<NodeArgs eType="User" icon="5" nRep="466" status="Passed" >
<Disp><![CDATA[     Verify  --> File size]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA[     Verify  --> File format]]></Obj>
<Details ><![CDATA[Actual=CIRI DOM 128  ; Expected=CIRI DOM 128 ]]></Details>
<Time><![CDATA[5/16/2011 - 9:04:10]]></Time>
<TimeTick>1305529450</TimeTick>
<NodeArgs eType="User" icon="5" nRep="467" status="Passed" >
<Disp><![CDATA[     Verify  --> File format]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[#32770]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/16/2011 - 9:06:51]]></Time>
<TimeTick>1305529611</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[WinObject.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["isabel"]]></Details>
<Time><![CDATA[5/16/2011 - 9:06:51]]></Time>
<TimeTick>1305529611</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[#32770]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = <br>simclass = #32770<br>Native Class = #32770<br>miccommentproperty = <br>is owned window = -1<br>is child window = 0<br>]]></Details>
<Time><![CDATA[5/16/2011 - 9:06:51]]></Time>
<TimeTick>1305529611</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[#32770]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/16/2011 - 9:06:51]]></Time>
<TimeTick>1305529611</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[WinObject.GetTOProperty "html id"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:06:51]]></Time>
<TimeTick>1305529611</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="488" status="Warning" >
<Disp><![CDATA[WinObject.GetTOProperty "html id"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj ><![CDATA[SmokeTest : Unexpected problem in 'Upload'.]]></Obj>
<Details ><![CDATA[Object_html_id = ]]></Details>
<Time><![CDATA[5/16/2011 - 9:06:51]]></Time>
<TimeTick>1305529611</TimeTick>
<NodeArgs eType="User" icon="5" nRep="489" status="Failed" >
<Disp><![CDATA[SmokeTest : Unexpected problem in 'Upload'.]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj ><![CDATA[Upload_dev2_5162011090651 AM.png]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:06:51]]></Time>
<TimeTick>1305529611</TimeTick>
<Action rID="T69">
<AName><![CDATA[SelectLogonProfile]]></AName>
<Step rID="T70">
<Obj ><![CDATA[LogonProfile2 found on portal.]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:06:59]]></Time>
<TimeTick>1305529619</TimeTick>
<NodeArgs eType="User" icon="5" nRep="529" status="Passed" >
<Disp><![CDATA[LogonProfile2 found on portal.]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/16/2011 - 9:06:53" eTime="5/16/2011 - 9:07:01" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="496" status="Passed" >
<Disp><![CDATA[SelectLogonProfile Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="User" icon="5" nRep="490" status="Passed" >
<Disp><![CDATA[Upload_dev2_5162011090651 AM.png]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="487" status="Failed" >
<Disp><![CDATA[#32770]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="483" status="Failed" nType="Parent description" >
<Disp><![CDATA[#32770]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="481" status="Failed" >
<Disp><![CDATA[WinObject.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="480" status="Failed" >
<Disp><![CDATA[#32770]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/16/2011 - 9:02:02" eTime="5/16/2011 - 9:07:02" passed="45" failed="1" warnings="3" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="113" status="Failed" >
<Disp><![CDATA[Upload Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T71">
<AName><![CDATA[SwitchSigner]]></AName>
<Step rID="T72">
<Obj ><![CDATA[=== START ACTION : SwitchSigner ===]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[5/16/2011 - 9:07:02]]></Time>
<TimeTick>1305529622</TimeTick>
<NodeArgs eType="User" icon="5" nRep="539" >
<Disp><![CDATA[=== START ACTION : SwitchSigner ===]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj ><![CDATA['View details' clicked for : stg_sepa_withdebtortag_be32000000000202.xml]]></Obj>
<Details ><![CDATA[Click done.]]></Details>
<Time><![CDATA[5/16/2011 - 9:07:04]]></Time>
<TimeTick>1305529624</TimeTick>
<NodeArgs eType="User" icon="5" nRep="545" status="Passed" >
<Disp><![CDATA['View details' clicked for : stg_sepa_withdebtortag_be32000000000202.xml]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj ><![CDATA['View details' appeared for : stg_sepa_withdebtortag_be32000000000202.xml]]></Obj>
<Details ><![CDATA[Button 'Audit Trail' has been found.]]></Details>
<Time><![CDATA[5/16/2011 - 9:07:06]]></Time>
<TimeTick>1305529626</TimeTick>
<NodeArgs eType="User" icon="5" nRep="547" status="Passed" >
<Disp><![CDATA['View details' appeared for : stg_sepa_withdebtortag_be32000000000202.xml]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj ><![CDATA['View details' clicked for : stg_sepa_withdebtortag_be32000000000202.xml]]></Obj>
<Details ><![CDATA[Click done.]]></Details>